# Generated by Django 2.1.2 on 2018-11-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp7_site', '0002_auto_20181117_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='admin', max_length=30)),
                ('password', models.TextField(default='c0067d4af4e87f00dbac63b6156828237059172d1bbeac67427345d6a9fda484')),
            ],
        ),
    ]
